
name: "main"

on:
  # Triggers the workflow on push or pull request events but only for the master branch 
    #  push:
    #branches: [ master ]

  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: test
jobs:

   license-scan:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run clear
      run: |
        echo ${{ github.repository }}
        sudo rm -rf $PWD/reports
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: check out the repository
      uses: actions/checkout@v2
    - name: dep-scan
      uses: AppThreat/dep-scan-action@master
      env:
        VULNDB_HOME: ${{ github.workspace }}/db 
        GITHUB_TOKEN: ${{ secrets.GHE_TOKEN }}

    - name: cat 
      run: cat reports/license-go.json
    - name: cat 
      run: cat reports/depscan-go.json
    - name: ls -l
      run: cd reports;ls -l
    - uses: actions/upload-artifact@v2
      with:
        name: reports
        path: './*.json*'
